version: '1.1'

services:
  web:
    build: .
    ports:
      - '8000:8080'
  db:
    image: 'postgres'
    ports:
      - '4321:5432'
    restart: 'always'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'emeeting'
    volumes:
      - './sql/initdata.sql:/docker-entrypoint-initdb.d/initdata.sql'
      